<?
$aMenuLinks = Array(
    Array(
        "Конкурсы",
        "/informacija/konkursy/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Партнерам",
        "/informacija/partneram/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Кредит",
        "/informacija/kredit/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Обмен и возврат",
        "/informacija/garantii/",
        Array(),
        Array(),
        ""
    )
);
?>