<?
define("HIDE_BOTTOM_PANEL", true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сравнение товаров");

    $idMap = array();
    foreach ($_SESSION['CATALOG_COMPARE_LIST'][8]['ITEMS'] as $item) {
        $idMap[] = $item['ID'];
    }

    if (count($idMap) > 0) {
        $offerIdMaps = array();

        $dbOffer = \CIBlockElement::GetList(
            array(),
            array(
                'IBLOCK_ID' => 25,
                'PROPERTY_CML2_LINK' => $idMap,
                'ACTIVE' => 'Y'
            ),
            false,
            false,
            array(
                'ID',
                'IBLOCK_ID',
                'NAME',
                'IBLOCK_SECTION_ID',
                'DETAIL_PICTURE',
                'DETAIL_PAGE_URL',
                'PROPERTY_VENDOR_CODE'
            )
        );
        while ($offer = $dbOffer->GetNext()) {
            $offerIdMaps[] = $offer['ID'];
            $offer["RESIZE_PICTURE"] = Helper::Resize(array($offer['DETAIL_PICTURE']), 210, 210, true);
            if ($offer["RESIZE_PICTURE"] == NULL) {
                $offer["RESIZE_PICTURE"]["SRC"] = SITE_TEMPLATE_PATH."/img/no-img-500.png";
                $offer["RESIZE_PICTURE"]["NO_PICTURE"] = "Y";
            }
            $_SESSION['CATALOG_COMPARE_LIST'][8]['ITEMS'][$offer['ID']] = $offer;
        }
    }

?>

<?$APPLICATION->IncludeComponent(
	"custom:catalog.compare.result",
	"compare", 
	array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/cart/",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_ELEMENT_SELECT_BOX" => "N",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD_BOX" => "name",
		"ELEMENT_SORT_FIELD_BOX2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"ELEMENT_SORT_ORDER_BOX2" => "desc",
		"FIELD_CODE" => array(
			0 => "DETAIL_PICTURE",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "catalog",
		"NAME" => "CATALOG_COMPARE_LIST",
		"PRICE_CODE" => $GLOBALS["CITY_PRICE_CODE"],
		"GEO_REGION_CITY_NAME" => $GLOBALS["GEO_REGION_CITY_NAME"],
		"REGION_PRICE_CODE_DEFAULT" => "Москва",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PROPERTY_CODE" => array(
			0 => "CHAR_TIP_SMAZKI",
			1 => "CHAR_TIP_MASHINY",
			2 => "CHAR_KOLICHESTVO_IGL_DLYA_VYSHIVANIYA",
			3 => "CHAR_POTREBLYAEMAYA_MOSHHNOST",
			4 => "CHAR_TIP_CHELNOKA",
			5 => "CHAR_KOLICHESTVO_IGL",
			6 => "CHAR_MAKSIMALNAYA_SKOROST_SHITYA",
			7 => "CHAR_REGULIROVKA_DAVLENIYA_LAPKI_NA_TKAN",
			8 => "CHAR_NITEVDEVATEL",
			9 => "CHAR_KOLICHESTVO_OPERACIJ",
			10 => "CHAR_AVTOMATICHESKOE_SMATYVANIE_SHNURA",
			11 => "CHAR_AVTONOMNAYA_SINXRONIZACIYA_S_PK",
			12 => "CHAR_BLOK_UPRAVLENIYA",
			13 => "CHAR_BLOKIROVKA_RUCHKI_PRESSA",
			14 => "CHAR_VES",
			15 => "CHAR_VIDY_STROCHEK",
			16 => "CHAR_VOZMOZHNOST_SINXRONIZACII_S_PK",
			17 => "CHAR_VREMYA_GOTOVNOSTI_PARA",
			18 => "CHAR_VREMYA_NEPRERYVNOJ_RABOTY",
			19 => "CHAR_VYPOLNENIE_PETEL",
			20 => "CHAR_VYSHIVALNYJ_BLOK",
			21 => "CHAR_DATCHIK_OBRYVA_NITI",
			22 => "CHAR_DIFFERENCIALNAYA_PODACHA_MATERIALA",
			23 => "CHAR_DLINA_SETEVOGO_SHNURA",
			24 => "CHAR_KOLICHESTVO_NITEJ",
			25 => "CHAR_KOLICHESTVO_FONTUR",
			26 => "CHAR_KOLICHESTVO_SHVEJNYX_OPERACIJ",
			27 => "CHAR_KOLICHESTVO_SHVOV",
			28 => "CHAR_KOLICHESTVO_SHRIFTOV_DLYA_MONOGRAMM",
			29 => "CHAR_KOLICHESTVO_YACHEEK_PAMYATI",
			30 => "CHAR_KONTROL_NATYAZHENIYA_NITEJ",
			31 => "CHAR_KORPUS",
			32 => "CHAR_LINEJKA_NA_KORPUSE",
			33 => "CHAR_MAKSIMALNAYA_VYSOTA_PODEMA_LAPKI",
			34 => "CHAR_MAKSIMALNAYA_DLINA_STEZHKA",
			35 => "CHAR_MAKSIMALNAYA_SKOROST_VYSHIVKI",
			36 => "CHAR_MAKSIMALNAYA_SHIRINA_STEZHKA",
			37 => "CHAR_MAKSIMALNYJ_RAZMER_VYSHIVKI",
			38 => "CHAR_MAKSIMALNYJ_RAZMER_PYALEC_V_KOMPLEKTE",
			39 => "CHAR_MUSOROSBORNIK",
			40 => "CHAR_NALICHIE_USB_PORTA",
			41 => "CHAR_NALICHIE_RUKAVNOJ_PLATFORMY",
			42 => "CHAR_NIZHNIJ_TRANSPORTER",
			43 => "CHAR_OBREZKA_NITEJ",
			44 => "CHAR_OBEM_BOJLERA",
			45 => "CHAR_OSVESHHENIE_RABOCHEJ_POVERXNOSTI",
			46 => "CHAR_PNEVMATICHESKAYA_ZAPRAVKA_NITI_V_PETLITELI",
			47 => "CHAR_PODDERZHIVAEMYE_FORMATY_VYSHIVKI",
			48 => "CHAR_PODSTAVKA_POD_PRESS",
			49 => "CHAR_POLE_SHITYA",
			50 => "CHAR_RAMNAYA_KONSTRUKCIYA",
			51 => "CHAR_RASPOLOZHENIE_REGULYATOROV_NATYAZHENIYA_NITEJ",
			52 => "CHAR_RASPOSHIVALNYJ_SHOV",
			53 => "CHAR_RASSTOYANIE_MEZHDU_IGLAMI",
			54 => "CHAR_ROLEVYJ_SHOV",
			55 => "CHAR_SINXRONIZACIYA_S_PK",
			56 => "CHAR_SISTEMA_AVTOOTKLYUCHENIYA",
			57 => "CHAR_SPOSOB_PROGRAMMIROVANIYA",
			58 => "CHAR_STANDART_IGL",
			59 => "CHAR_SEMNAYA_RUKAVNAYA_PLATFORMA",
			60 => "CHAR_TIP_DISPLEYA",
			61 => "CHAR_TIP_OBRABATYVAEMOJ_PRYAZHI",
			62 => "CHAR_USTROJSTVO_OBREZKI_NITI",
			63 => "CHAR_CILINDRICHESKAYA_RAMA",
			64 => "CHAR_SHOV_FLATLOCK",
			65 => "CHAR_AVTOMATICHESKIJ_NITEVDEVATEL",
			66 => "CHAR_VES_VYAZALNOJ_MASHINY",
			67 => "CHAR_ISPOLZOVANIE_PROGRAMMNOGO_OBESPECHENIYA",
			68 => "CHAR_KLASS_MASHINY",
			69 => "CHAR_PODDERZHKA_NOSITELEJ_INFORMACII",
			70 => "CHAR_RAZMER_RABOCHEJ_POVERXNOSTI_PRESSA",
			71 => "CHAR_TIP_NOSITELEJ_INFORMACII",
			72 => "",
		),
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "red",
		"USE_PRICE_COUNT" => "N",
		"COMPONENT_TEMPLATE" => "compare",
		"OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		)
	),
	false
);

?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>